### ISSUE TITLE
Random client side crash

### ISSUE THREAD

**Issue by canitzp** [OpenModularTurretsTeam/OMLib#1]
With my custom modpack on my server one of my players experience a random crash when he want to do something with OpenModularTurrets.

[crash-report](https://pastebin.com/V4tL0rJp)
All important informations can be get out of the crash-report

This is maybe also related to BetterFoliage, but I only open a issue there if it really is.

**Comment by Keridos** [comment]
Nah seems to be caused by Omlib, will push a commit that should fix that: Try this please: https://jenkins.ironhide.de/job/OMLib%201.10.2/64/

**Comment by canitzp** [comment]
Your link is the 1.10.2 version of OMLib, I can only test it with a 1.11.2 version, but I can't directly test it, cause I have to make a modpack update and this isn't planned in the next time

**Comment by Keridos** [comment]
Sorry, was not OMLib, try the latest OpenModularTurrets please. Test with this please: https://jenkins.ironhide.de/job/OMLib%201.11.2/65/
and this:
https://jenkins.ironhide.de/job/OpenModularTurrets-1.10.2/113/

**Comment by Keridos** [comment]
Is this fixed? @canitzp

**Comment by canitzp** [comment]
Sorry I have no time currently to maintain the pack and the server.
