### ISSUE TITLE
3.2.0-250 class not find, crashing dedicated server.

### ISSUE THREAD

**Issue by kreezxil** [OpenModularTurretsTeam/OMLib#19]
https://gist.github.com/dad74ba8609f049d73e9dc4b9b0841f0

**Comment by kreezxil** [comment]
interestingly i rolled openmodular turrets down to the jan 30th release and it is still giving me this crash in the lib. 

 
https://gist.github.com/a53230b140a4d3dc46d3fb02b566faf0

**Comment by Keridos** [comment]
You should either use OMLib 3.1.x and OMT 3.1.x OR both at 3.2.0, not mixing
