### ISSUE TITLE
OMT doesn't detect latest version of OMLib

### ISSUE THREAD

**Issue by BugmanBugman** [OpenModularTurretsTeam/OMLib#21]
Doesn't work with the latest version of OpenModularTurrets

**Comment by Keridos** [comment]
Which latest?

**Comment by Keridos** [comment]
Also, cannot reproduce everything works fine for me.

**Comment by Keridos** [comment]
You are 99,999% using 3.1.x OMT with 3.2.x OMLib, minecraft should tell you that that doesnt work.
Most likely you exactly get this message: (you need omlib between 3.1.4.249 and 3.1.99-9999, you have 3.2.0-254)
