### ISSUE TITLE
Crashed When Disconnect From My Server

### ISSUE THREAD

**Issue by ghost** [OpenModularTurretsTeam/OMLib#3]
[crash-2017-05-23_21.55.43-client.txt](https://github.com/OpenModularTurretsTeam/OMLib/files/1023400/crash-2017-05-23_21.55.43-client.txt)
my client crashed when i disconnect my dedicated server which runs on the same pc.

**Comment by sandalle** [comment]
I get the same crash when disconnecting from my dedicated server after updating to OMLib 1.11.2-3.0.0-91.

Crash report: 
[crash-2017-05-23_21.46.04-client.txt](https://github.com/OpenModularTurretsTeam/OMLib/files/1024445/crash-2017-05-23_21.46.04-client.txt)

**Comment by Keridos** [comment]
https://jenkins.ironhide.de/job/OMLib%201.11.2/lastSuccessfulBuild/artifact/build/libs/omlib-1.11.2-3.0.0-92.jar, please see if that fixes it. 1.10.2 here: https://jenkins.ironhide.de/job/OMLib%201.10.2/lastSuccessfulBuild/artifact/build/libs/omlib-1.10.2-3.0.0-93.jar

**Comment by sandalle** [comment]
I get a 404 for the 1.11.2 build https://jenkins.ironhide.de/job/OMLib%201.11.2/lastSuccessfulBuild/artifact/build/libs/omlib-1.11.2-3.0.0-92.jar, but https://jenkins.ironhide.de/job/OMLib%201.11.2/lastSuccessfulBuild/artifact/build/libs/omlib-1.11.2-3.0.0-93.jar downloaded. ;)

I still crash when disconnecting, here's the updated crash report: [crash-2017-05-23_23.10.03-client.txt](https://github.com/OpenModularTurretsTeam/OMLib/files/1024544/crash-2017-05-23_23.10.03-client.txt)

**Comment by Keridos** [comment]
https://jenkins.ironhide.de/job/OMLib%201.11.2/94/artifact/build/libs/omlib-1.11.2-3.0.0-94.jar
I was too dumb to read the crash log correctly -.- Derp

**Comment by ghost** [comment]
this is fixed version?

**Comment by Keridos** [comment]
According to the crash log it should be. I know why this happened now.

**Comment by ghost** [comment]
okay, thanks.

**Comment by sandalle** [comment]
Build 1.11.2-3.0.0-94 fixed it for me, thanks!
