### ISSUE TITLE
MC-1.10.2 - Looking for 127 Omlib 3.0.0 but I can't find it online.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [OpenModularTurretsTeam/OMLib#9]
![33](https://user-images.githubusercontent.com/10351221/29937301-b6d413f4-8e4a-11e7-9b7e-9cf01659e1bc.PNG)

Why is asking for a version that has not been released?

**Comment by Starhero** [comment]
Ditto, Downgrading until fixed.

**Comment by Keridos** [comment]
Uploaded it to curseforge. Sorry for that derp.
